### ISSUE TITLE
Audit uses of LCG

### ISSUE THREAD

**Issue by Raynos** [uber/tchannel-node#212]
We are generating trace id using a small cycle LCG and we should use a better thing (xorshift)

c @jcorbin

**Comment by jcorbin** [comment]
The LCG in `lib/lcg.js` was meant to be used as a test fixture only.  Its constants are straight out of the table in https://en.wikipedia.org/wiki/Linear_congruential_generator (MSVC++ for 32-bits), and likely quite short cycle.
