### ISSUE TITLE
Implement tchannelAsThrift.getEndpointNames()

### ISSUE THREAD

**Issue by Willyham** [uber/tchannel-node#249]
@kriskowal 

TChannel 3.5.19 now depends on thriftrw 3.x which is a breaking change. As such, anybody consuming the output of `TChannelAsThrift` will break. I believe this should justify a major version bump.

**Comment by Raynos** [comment]
We manually verified and I think we only broke internal details.

The public interface of thriftrw changed, but tchannel as thrift did not change.

Please open issues about concrete things that broke so we can fix them.

**Comment by kriskowal** [comment]
TChannelAsThrift’s "spec" property is not public. Having discussed this with you offline, we have decided to add a "tchannelAsThrift.getEndpointNames()" method that will provide the functionality you need going forward in a minor update to TChannel proper.
