### ISSUE TITLE
suggest upgrade farmhash to version `1.1.1`

### ISSUE THREAD

**Issue by fanweixiao** [uber/tchannel-node#315]

**Comment by Raynos** [comment]
Looks like the only change between 1.1.0 and 1.1.1 is https://github.com/lovell/farmhash/commit/0dec098bd78ad67d7e84c436bc2fe119c1d07466

I don't think there is a need for upgrading to 1.1.1 ?

**Comment by fanweixiao** [comment]
Version 1.1.1 match this commit: https://github.com/lovell/farmhash/commit/954e89d56993877d91d0819d70768d589a83f3fb 

Seems by upgrade `nan` from `2.0.x` to `2.2.x` to ensure Node v5 support, I got problem when installing `farmhash@1.1.0`, but `1.1.1` version seems ok.

**Comment by Raynos** [comment]
I see.

**Comment by Raynos** [comment]
I've just verified tchannel locally againts v5.9.0 of nodejs.

It installs fine. Seeing a bunch of test failures, but not related to farmhash.

Can you report what the `farmhash@1.1.0` failure is and which OS ?

**Comment by fanweixiao** [comment]
Oh, I am trying repro this on a clean system, It's OK. Sorry for mistake issue.
